# Generated by Django 5.0.2 on 2024-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='age',
        ),
        migrations.AddField(
            model_name='appuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
