# Generated by Django 5.0.2 on 2024-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dailyscore_appuser_daily_scores_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='atrial_fib',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='diabetes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='hypertension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='ihd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='muscular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
