# Generated by Django 5.0.2 on 2024-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_atrial_fib_appuser_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='smoking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
