# Generated by Django 5.0.2 on 2024-02-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicine_dosage_alter_dailyscore_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
    ]
